complete_from_path = true
ctrlc_exit = false
path = ["C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.9.1942.0_x64__8wekyb3d8bbwe", "C:\\Program Files\\Alacritty\\", "C:\\Windows\\system32", "C:\\Windows", "C:\\Windows\\System32\\Wbem", "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\", "C:\\Windows\\System32\\OpenSSH\\", "C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR", "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common", "C:\\Program Files\\dotnet\\", "C:\\Program Files\\PowerShell\\7\\", "C:\\WINDOWS\\system32", "C:\\WINDOWS", "C:\\WINDOWS\\System32\\Wbem", "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\", "C:\\WINDOWS\\System32\\OpenSSH\\", "C:\\Program Files\\Git\\cmd", "C:\\Program Files (x86)\\Yarn\\bin\\", "C:\\Program Files\\Vim\\vim82", "C:\\Program Files\\nvim\\bin", "C:\\Program Files\\nu\\bin\\", "C:\\Users\\pradeep\\Tools", "C:\\Users\\pradeep\\AppData\\Local\\Programs\\Python\\Python39\\", "C:\\Users\\pradeep\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\", "C:\\Users\\pradeep\\.cargo\\bin", "C:\\Users\\pradeep\\AppData\\Local\\Yarn\\bin", "C:\\Users\\pradeep\\scoop\\shims", "C:\\Users\\pradeep\\AppData\\Local\\Microsoft\\WindowsApps", "C:\\Users\\pradeep\\AppData\\Local\\Programs\\Microsoft VS Code\\bin", "C:\\Users\\pradeep\\AppData\\Local\\Pandoc"]
prompt = "starship prompt"
rm_always_trash = true
skip_welcome_message = true
startup = ["alias o = explorer", "alias gaa = git add .", "alias gs = git status", "alias gcm = git commit -am", "alias gl = git log --decorate --oneline --graph", "alias gi = git init", "alias gc = git checkout", "alias gcb = git checkout -b", "alias gpush = git push", "alias v = vim", "alias nv = nvim", "alias np = notepad", "alias wg = winget", "def clr [] { clear }", "def cls [] { clear }", "def gconf [ac: int] { let gitprofiles = [\"75474807+iamprady@users.noreply.github.com\", \"85151832+pradeep-gox@users.noreply.github.com\"]\ngit config user.email ($gitprofiles | nth $ac)}","fnm env --shell bash | lines | last 5 | str find-replace 'export ' '' | str find-replace -a '\"' '' | split column = | rename name value | load-env","pathvar add $nu.env.FNM_MULTISHELL_PATH"]
table_mode = "rounded"

[color_config]
header_align = "l"
header_bold = true
header_color = "c"
index_color = "y"
primitive_path = "g"

[env]
"=::" = "::\\"
ALLUSERSPROFILE = "C:\\ProgramData"
APPDATA = "C:\\Users\\pradeep\\AppData\\Roaming"
CMD_DURATION_MS = "1"
COMPUTERNAME = "LEGION-Y530"
ComSpec = "C:\\WINDOWS\\system32\\cmd.exe"
CommonProgramFiles = "C:\\Program Files\\Common Files"
"CommonProgramFiles(x86)" = "C:\\Program Files (x86)\\Common Files"
CommonProgramW6432 = "C:\\Program Files\\Common Files"
DriverData = "C:\\Windows\\System32\\Drivers\\DriverData"
FPS_BROWSER_APP_PROFILE_STRING = "Internet Explorer"
FPS_BROWSER_USER_PROFILE_STRING = "Default"
HOMEDRIVE = "C:"
HOMEPATH = "\\Users\\pradeep"
LOCALAPPDATA = "C:\\Users\\pradeep\\AppData\\Local"
LOGONSERVER = "\\\\LEGION-Y530"
NUMBER_OF_PROCESSORS = "12"
OS = "Windows_NT"
OneDrive = "C:\\Users\\pradeep\\OneDrive"
PATHEXT = ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
POWERSHELL_DISTRIBUTION_CHANNEL = "MSI:Windows 10 Home"
PROCESSOR_ARCHITECTURE = "AMD64"
PROCESSOR_IDENTIFIER = "Intel64 Family 6 Model 158 Stepping 10, GenuineIntel"
PROCESSOR_LEVEL = "6"
PROCESSOR_REVISION = "9e0a"
PSModulePath = "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules"
PUBLIC = "C:\\Users\\Public"
ProgramData = "C:\\ProgramData"
ProgramFiles = "C:\\Program Files"
"ProgramFiles(x86)" = "C:\\Program Files (x86)"
ProgramW6432 = "C:\\Program Files"
SESSIONNAME = "Console"
SystemDrive = "C:"
SystemRoot = "C:\\WINDOWS"
TEMP = "C:\\Users\\pradeep\\AppData\\Local\\Temp"
TMP = "C:\\Users\\pradeep\\AppData\\Local\\Temp"
USERDOMAIN = "LEGION-Y530"
USERDOMAIN_ROAMINGPROFILE = "LEGION-Y530"
USERNAME = "pradeep"
USERPROFILE = "C:\\Users\\pradeep"
VBOX_MSI_INSTALL_PATH = "C:\\Program Files\\Oracle\\VirtualBox\\"
WSLENV = "WT_SESSION::WT_PROFILE_ID"
WT_PROFILE_ID = "{2b372ca1-1ee2-403d-a839-6d63077ad871}"
WT_SESSION = "f2d2bba5-c728-46f6-8ae9-5f08e8cd0083"
ZES_ENABLE_SYSMAN = "1"
__COMPAT_LAYER = "DetectorsShimLog"
windir = "C:\\WINDOWS"

[line_editor]
bell_style = "none"
max_history_size = 1000

[textview]
colored_output = true
grid = false
header = true
line_numbers = false
pager = "less"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 4
term_width = "default"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "NoWrapping"
